const functions = require("firebase-functions");
const admin = require("firebase-admin");
admin.initializeApp();

exports.seedVehicleCatalog = functions.https.onRequest(async (req, res) => {
  const catalogData = {
    colors: [
      "White",
      "Silver",
      "Grey",
      "Black",
      "Blue",
      "Red",
      "Maroon",
      "Brown",
      "Beige",
      "Green",
      "Yellow",
      "Orange",
      "Purple",
      "Pink",
      "Gold",
    ],
    private: {
      "Maruti Suzuki": [
        "Swift",
        "Dzire",
        "Baleno",
        "Wagon R",
        "Alto K10",
        "Ertiga",
        "Vitara Brezza",
        "Grand Vitara",
        "Fronx",
        "Jimny",
        "Celerio",
        "Ignis",
        "XL6",
      ],
      "Tata": [
        "Tiago",
        "Nexon",
        "Punch",
        "Altroz",
        "Harrier",
        "Safari",
        "Tigor EV",
        "Nexon EV",
        "Punch EV",
      ],
      "Hyundai": [
        "Creta",
        "Venue",
        "i20",
        "Grand i10 Nios",
        "Verna",
        "Alcazar",
        "Exter",
      ],
      "Mahindra": [
        "Thar",
        "XUV700",
        "Scorpio N",
        "Bolero",
        "Bolero Neo",
        "XUV300",
        "XUV400 EV",
      ],
      "Kia": ["Seltos", "Sonet", "Carens", "Carnival", "EV6"],
      "Toyota": [
        "Innova Crysta",
        "Fortuner",
        "Urban Cruiser Hyryder",
        "Glanza",
        "Rumion",
      ],
      "Honda": ["City", "Amaze", "Elevate", "WR-V"],
      "MG": ["Hector", "Astor", "ZS EV", "Comet EV", "Windsor EV"],
      "Skoda": ["Kushaq", "Slavia", "Kodiaq"],
      "Volkswagen": ["Virtus", "Taigun", "Tiguan"],
      "Jeep": ["Compass", "Meridian"],
      "Renault": ["Kiger", "Triber", "Duster"],
      "Nissan": ["Magnite"],
      "Citroen": ["C3", "C3 Aircross", "eC3"],
      "BYD": ["Atto 3", "Seal", "e6"],
      "Maruti Suzuki Victoris": ["Victoris"],
      "Luxury Brands": {
        "Mercedes-Benz": [
          "A-Class",
          "C-Class",
          "E-Class",
          "GLA",
          "GLC",
          "GLE",
          "GLS",
        ],
        "BMW": ["X1", "X3", "X5", "3 Series", "5 Series"],
        "Audi": ["Q3", "Q5", "A4", "A6", "e-tron"],
        "Volvo": ["XC40", "XC60", "XC90", "C40 Recharge"],
        "Lexus": ["NX350h", "RX500h"],
        "Jaguar Land Rover": ["Discovery Sport", "Range Rover Evoque"],
      },
      "EV Startups": {
        "Pravaig": ["Defy EV"],
        "Strom Motors": ["Strom R3"],
        "Ola Electric": ["Ola EV Car (Upcoming)"],
      },
    },
    commercial: {
      "Tata": [
        "Ace Gold",
        "Intra",
        "407 Gold",
        "Prima",
        "Signa 4825.C",
        "Ultra EV",
        "Starbus",
        "T.11 EV",
      ],
      "Mahindra": [
        "Jeeto",
        "Bolero Pik-Up",
        "Bolero Maxitruck Plus",
        "Blazo XPR",
        "e-Alfa",
        "Treo Zor",
      ],
      "Ashok Leyland": [
        "Dost",
        "BADA DOST",
        "Partner",
        "Ecomet",
        "AVSR Tipper",
        "Circuit Electric Bus",
      ],
      "Eicher": [
        "Pro 2049",
        "Pro 6028T Tanker",
        "Skyline Bus",
        "Eicher Electric Truck",
      ],
      "BharatBenz": [
        "Medium Duty Trucks",
        "Heavy Duty Trucks",
        "Staff Bus",
        "School Bus",
      ],
      "Force": ["Urbania", "Traveller Delivery Van", "Traveller School Bus"],
      "Maruti Suzuki": ["Super Carry"],
      "Bajaj": ["RE Tempo", "Ape 3-Wheeler"],
      "Piaggio": ["Ape City", "Porter", "Ape Electric"],
      "OSM": ["Swayamgati EV"],
      "Montra Electric": ["Rhino 5538 EV"],
      "Euler Motors": ["Turbo EV 1000"],
      "Isuzu": ["D-Max Pickup"],
      "Volvo": ["FMX Tanker", "B11R Coach"],
      "Scania": ["G Series Container", "Intercity Bus"],
      "BYD": ["e6 Cargo", "T3 Electric Van"],
      "Altigreen": ["NeEV Cargo EV"],
      "Agricultural": {
        "Mahindra Tractors": ["275 DI TU", "Arjun Novo 605", "Yuvo Tech+"],
        "Swaraj": ["744 FE", "735 FE"],
        "Sonalika": ["DI 750 III", "Tiger 55"],
        "Eicher Tractors": ["485 Super Plus", "5660"],
      },
    },
  };
  await admin
      .firestore()
      .collection("vehicleCatalog")
      .doc("india2025")
      .set(catalogData);
  res.status(200).send("Vehicle catalog seeded successfully.");
});
